### ISSUE TITLE
not written in HolyC

### ISSUE THREAD

**Issue by Crystallinqq** [T4zzuu/templehook#1]
important issue.

**Comment by fee1-dead** [comment]
Agreed.

**Comment by benrimk** [comment]
Agreed.

**Comment by ghost** [comment]
really poor developing imho.
overlooked such an important subject.
3/10 for effort from devs, smh my head.

**Comment by notbemji** [comment]
holyc is written specifically for templeos and does not have any officially supported compilers for windows x86.
write a compiler and send me it.

**Comment by ghost** [comment]
It was a joke and obvious satire.
